#ifndef __KEYBOARD_H__
#define __KEYBOARD_H__

#include "main.h"
#include "stm32f1xx_hal.h"
#include <string.h>

char KEY_SCAN(void);
char KEY_ROW_SCAN(void);
void HW_KEY_FUNCTION(void);

#define KEY_CLO1_OUT_LOW  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_0,GPIO_PIN_RESET) 
#define KEY_CLO2_OUT_LOW  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_1,GPIO_PIN_RESET)
#define KEY_CLO3_OUT_LOW  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_2,GPIO_PIN_RESET)
#define KEY_CLO4_OUT_LOW  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_3,GPIO_PIN_RESET)

#define KEY_CLO1_OUT_HIGH  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_0,GPIO_PIN_SET) 
#define KEY_CLO2_OUT_HIGH  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_1,GPIO_PIN_SET)
#define KEY_CLO3_OUT_HIGH  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_2,GPIO_PIN_SET)
#define KEY_CLO4_OUT_HIGH  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_3,GPIO_PIN_SET)

#endif
